### PR TITLE
Fix #1609

### LINKED ISSUE #1609: [Bug Report] Discarded `:` in Help Buffer's Ex Mode
@fox0430

This is a minor visual bug.

With the latest available repository state of Moe, open any file.  Now, call `:help` and switch to the help buffer.  If the help buffer is active, the initial `:` in Ex Mode will be discarded visually, and only visually; any command will work as usual.  This only affects the help buffer if it is opened and active.

### PR DESCRIPTION
**Pull request by fox0430**
Fix a bug in that the prompt is not displayed when changing the mode from help to ex.

Close #1609

### CODE REVIEW

File: tests/thelp.nim [hunk 1]
```diff
@@ -1,13 +1,32 @@
...
+import std/[unittest, strutils, importutils]
+import moepkg/[unicodeext, gapbuffer, editorstatus, bufferstatus]
 
 import moepkg/helputils {.all.}
+import moepkg/help {.all.}
+import moepkg/commandline {.all.}
 
-suite "Help":
+suite "initHlepModeBuffer":
   test "initHlepModeBuffer":
```
Comment (kevinmatthes) [inline tests/thelp.nim]: @fox0430

Please fix the typo `Hlep` (`e` and `l` exchanged) in lines 8 and 9.

```suggestion
suite "initHelpModeBuffer":
  test "initHelpModeBuffer":
```

File: changelog.d/20230203_081121_shuu.n_fix_1609.rst [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+..
+.. Deprecated
+.. ..........
+..
+.. - A bullet item for the Deprecated category.
+
+Fixed
+.....
+
+- `#1610`_ Fix #1609
```
Comment (kevinmatthes) [inline changelog.d/20230203_081121_shuu.n_fix_1609.rst]: @fox0430

How about also linking the issue?

**Review by kevinmatthes — CHANGES_REQUESTED** [review]
@fox0430

Thank you for your fix of the described bug!  I had a look at the changes and would like to suggest two small things explained below.

**Review by kevinmatthes — APPROVED** [review]
